# -*- coding: utf-8 -*-
"""wordcloudcami.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10nFUnzePEkPNKXniKXjGXRedplmxLyRq
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install pillow

import pandas as pd
from wordcloud import WordCloud, ImageColorGenerator
import matplotlib.pyplot as plt
from PIL import Image
import numpy as np

df = pd.read_csv('/content/opiniones_iava22.csv')
df

texto = '   '.join(df['Opinion'].dropna())
texto

wc = WordCloud(width=800, height=800, background_color='white', min_font_size=10).generate(texto)
plt.imshow(wc)
plt.axis('off')
plt.show()